
apiVersion: projects.argocd.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
spec:
  forProvider:
    projectLabels:
      argocd.crossplane.io/global-project: "true"
    sourceNamespaces:
      - default
    destinations:
      - namespace: default
        server: https://kubernetes.default.svc
    sourceRepos:
      - https://github.com/stefanprodan/podinfo/
  providerConfigRef:
    name: default
---
apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  name: example-application
spec:
  forProvider:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: example-project
    source:
      path: charts/podinfo
      repoURL: https://github.com/stefanprodan/podinfo/
      targetRevision: HEAD
  providerConfigRef:
    name: default
